name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:  
      - master

jobs:
  unit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16, 17]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run lint
    - run: npm test
